/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene/conf.ls
 */
export class ConfSceneBase extends Laya.Scene {
    public snd!: Laya.Clip;
    public msc!: Laya.Clip;
    public epb!: Laya.Button;
}

