/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene/explan.ls
 */
export class ExplanSceneBase extends Laya.Scene {
    public back!: Laya.Button;
}

