/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * GameStart.ls
 */
export class GameStartBase extends Laya.Scene {
    public startBtn!: Laya.Button;
}

