/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene/Game.ls
 */
export class GameBase extends Laya.Scene {
    public scoreNums!: Laya.Box;
    public timerBar!: Laya.ProgressBar;
    public GameOver!: Laya.Box;
    public scoreNumsSettlement!: Laya.Box;
    public restartBtn!: Laya.Button;
    public SoundButton!: Laya.Button;
    public PauseButton!: Laya.Button;
    public CloseButton!: Laya.Button;
    public AimScore!: Laya.Box;
    public checkpoint!: Laya.Box;
    public Start!: Laya.Image;
    //public GameOver!: Laya.Image;
    public pass!: Laya.Image;
    public backButton!: Laya.Button;
    public countDown!: Laya.Clip;
    public hammer!: Laya.Image;
}

