/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Game.ls
 */
export class GameBase extends Laya.Scene {
    public normal!: Laya.Image;
    public hit!: Laya.Image;
}

