/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Game.ls
 */
export class GameBase extends Laya.Scene {
    public scoreNums!: Laya.Box;
    public timerBar!: Laya.ProgressBar;
    public hammer!: Laya.Image;
}

