/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene/loading.ls
 */
export class LoadingSceneBase extends Laya.Scene {
    public progress!: Laya.ProgressBar;
}

