/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene/start.ls
 */
export class StartSceneBase extends Laya.Scene {
    public confBtn!: Laya.Button;
    public startBtn!: Laya.Button;
    public explanBtn!: Laya.Button;
    public existBtn!: Laya.Button;
}

